## Headline: 
## Main research question: 
## Project description:

## Importing  & Pip Install Cell

In [2]:
!pip install pymdbtools --quiet

ERROR: Could not find a version that satisfies the requirement pymdbtools (from versions: none)

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
ERROR: No matching distribution found for pymdbtools

In [3]:
import os
import re

from pathlib import Path
import configparser

import geopandas as gpd
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import requests
from ruamel.yaml import YAML

In [4]:
#from mdbtools import Mdb

## Data Check: Germany

In [5]:
prtr_ger = pd.read_excel("/home/sarah/Documents/projects/2026/Toxic Zones/germany/E-PRTR_Deutschland_2007-2024_2026-03-20.xlsx")

In [6]:
prtr_ger.sample(5)

,Liste mit Informationen zu der Fachdatenberichterstattung E-PRTR,Unnamed: 1
2,Hinweis:,Die Liste enthält den Gesamtdatenbestand der P...
0,Hintergrund der Veröffentlichung:,Die Fachdatenberichterstattung E-PRTR ist eine...
3,Stand der Daten:,2025-12-10 00:00:00
1,Herkunft der Daten:,"Die in den Listen „Freisetzung“, „Abwasser“ un..."
4,Berichtsjahr:,2007-2024

## Data Upload Cell: EPRTR Air and EPRTR Water

In [7]:
## EPRTR Data on Water

eprtr_w = pd.read_csv("/home/sarah/Documents/projects/2026/Toxic Zones/eprtr_data/eea_t_ied-eprtr_p_2007-2024_v16_r00/User friendly .csv files/F2_4_Water_Releases_Facilities.csv")

## EPRTR Data on Air

eprtr_a = pd.read_csv("/home/sarah/Documents/projects/2026/Toxic Zones/eprtr_data/eea_t_ied-eprtr_p_2007-2024_v16_r00/User friendly .csv files/F1_4_Air_Releases_Facilities.csv")

## EPRTR Data on Soil

/tmp/ipykernel_221216/2792726462.py:3: DtypeWarning: Columns (15) have mixed types. Specify dtype option on import or set low_memory=False.
  eprtr_w = pd.read_csv("/home/sarah/Documents/projects/2026/Toxic Zones/eprtr_data/eea_t_ied-eprtr_p_2007-2024_v16_r00/User friendly .csv files/F2_4_Water_Releases_Facilities.csv")

In [8]:
eprtr_w.head(2)

,PublicationDate,countryName,reportingYear,EPRTR_SectorCode,EPRTR_SectorName,EPRTRAnnexIMainActivity,FacilityInspireId,facilityName,city,Longitude,Latitude,addressConfidentialityReason,TargetRelease,Pollutant,Releases,confidentialityReason
0,2026/02/13,United Kingdom,2014,1.0,Energy sector,1(c),UK.CAED/BEISOffsh-Forties-Alpha.FACILITY,Forties Alpha,--,0.58217,57.43551,NaN,WATER,Anthracene,12.1,NaN
1,2026/02/13,Germany,2011,4.0,Chemical industry,4(b)(iv),https://registry.gdi-de.org/id/de.nw.inspire.p...,Solvay GmbH,Rheinberg,6.57783,51.56471,NaN,WATER,Cadmium and compounds (as Cd),113.0,NaN

In [9]:
#eprtr_w.info()

In [10]:
eprtr_a.head(2)

,PublicationDate,countryName,reportingYear,EPRTR_SectorCode,EPRTR_SectorName,EPRTRAnnexIMainActivity,FacilityInspireId,facilityName,city,Longitude,Latitude,addressConfidentialityReason,TargetRelease,Pollutant,Releases,confidentialityReason
0,2026/02/13,Germany,2013,1.0,Energy sector,1(e),https://registry.gdi-de.org/id/de.nw.inspire.p...,RWE Power AG-Fabrik Fortuna Nord,Bergheim,6.65805,50.98695,NaN,AIR,Sulphur oxides (SOX),824000.0,NaN
1,2026/02/13,Sweden,2020,7.0,Intensive livestock production and aquaculture,7(a)(i),SE.CAED/10017896.Facility,Skåneägg Produktion AB,MÖRARP,12.84955,56.05316,NaN,AIR,Ammonia (NH3),16300.0,NaN

## Reported Pollutants

In [11]:
# reported pollutants to water

poll_w = eprtr_w["Pollutant"].unique()
#print(poll_w)
#list(poll_w)
eprtr_w.columns

len(poll_w)

81

In [12]:
# reported pollutants to air

#eprtr_a.columns
#eprtr_a.sample(3)

#eprtr_a["Pollutant"].unique()

poll_a = eprtr_a["Pollutant"].unique()
print(poll_a)

print(len(poll_a))

['Sulphur oxides (SOX)' 'Ammonia (NH3)' 'Methane (CH4)'
 'Particulate matter (PM10)' 'Chlorofluorocarbons (CFCs)'
 'Carbon dioxide (CO2)' 'Nitrous oxide (N2O)'
 'Fluorine and inorganic compounds (as HF)'
 'Chlorine and inorganic compounds (as HCl)' 'Naphthalene'
 'Cadmium and compounds (as Cd)' 'Nitrogen oxides (NOX)'
 'Hydro-fluorocarbons (HFCS)' 'Nickel and compounds (as Ni)'
 'Hydrochlorofluorocarbons (HCFCs)'
 'Non-methane volatile organic compounds (NMVOC)'
 'Zinc and compounds (as Zn)' 'Hydrogen cyanide (HCN)'
 'Carbon dioxide (CO2) excluding biomass' 'Mercury and compounds (as Hg)'
 'Benzene' 'Polycyclic aromatic hydrocarbons (PAHs)'
 'Carbon monoxide (CO)' 'Chromium and compounds (as Cr)'
 'Perfluorocarbons (PFCs)' 'Arsenic and compounds (as As)' 'Anthracene'
 'PCDD + PCDF (dioxins + furans) (as Teq)'
 'Polychlorinated biphenyls (PCBs)' '1,1,1-trichloroethane (TCE-1,1,1)'
 'Lead and compounds (as Pb)' 'Dichloromethane (DCM)'
 'Total organic carbon(as total C or COD/3) (TOC)'
 'Copper and compounds (as Cu)' '1,2-dichloroethane (DCE-1,2)'
 'Trichlorobenzenes (TCB)' 'Benzo(g,h,i)perylene'
 'Fine particulate matter (PM2.5)' 'Vinyl chloride'
 'Sulphur hexafluoride (SF6)' 'Trichloromethane'
 '1,1,2,2-tetrachloroethane (TETRACHLOROETHANE-1,1,2,2)' 'Fluoranthene'
 'Tetrachloroethylene' 'Halons' 'Ethyl benzene' 'Phenols (as total C)'
 'CONFIDENTIAL' 'Tetrachloromethane (TCM)' 'Fluorides (as total F)'
 'Ethylene oxide' 'Trichloroethylene (TRI)'
 'Di-(2-ethyl hexyl) phthalate (DEHP)' 'Chlorides (as total Cl)'
 'Hexachlorobenzene (HCB)' 'Toluene' 'Aldrin' 'Pentachlorobenzene'
 'Pentachlorophenol (PCP)' 'Nonylphenol and Nonylphenol ethoxylates'
 'Halogenated organic compounds (as AOX)' 'Asbestos' 'Endrin' 'Lindane'
 'Total nitrogen' 'Chlordecone' 'Xylenes'
 '1,2,3,4,5,6-hexachlorocyclohexane (HCH)'
 'Brominated diphenylethers (PBDE)']
69

In [13]:
# reported pollutants to land - unclear

## Basic E-PRTR Pollutants Mapping Sheet

In [14]:
# unique_count = len(poll_w)
# print(unique_count)

In [15]:
class_sheet = pd.DataFrame(poll_w, columns = ['name'])
class_sheet['medium'] = 'water' 

class_sheet.head(2)

                            name medium
0                     Anthracene  water
1  Cadmium and compounds (as Cd)  water

In [16]:
def classify_by_parentheses(name):
    """Check if the name ends with (ABC) pattern"""
    # Match any characters ending with (content) at the end of string
    if re.search(r'\([^)]+\)$', str(name)):
        return 'group'
    else:
        return 'single'

class_sheet['type'] = class_sheet['name'].apply(classify_by_parentheses)

class_sheet.head(2)

                            name medium    type
0                     Anthracene  water  single
1  Cadmium and compounds (as Cd)  water   group

In [17]:
# adding air pollutants to dataframe
# Convert to sets for efficient matching
water_set = set(poll_w)
air_set = set(poll_a)

water_only = water_set - air_set
air_only = air_set - water_set
both_lists = water_set & air_set

print(both_lists)
len(both_lists)

{'Nonylphenol and Nonylphenol ethoxylates', 'Nickel and compounds (as Ni)', 'Chromium and compounds (as Cr)', '1,2-dichloroethane (DCE-1,2)', 'Pentachlorophenol (PCP)', 'Mercury and compounds (as Hg)', 'Anthracene', '1,2,3,4,5,6-hexachlorocyclohexane (HCH)', '1,1,2,2-tetrachloroethane (TETRACHLOROETHANE-1,1,2,2)', 'Tetrachloromethane (TCM)', 'Ethylene oxide', 'Halogenated organic compounds (as AOX)', 'Polychlorinated biphenyls (PCBs)', 'Carbon monoxide (CO)', 'CONFIDENTIAL', 'Asbestos', 'Hexachlorobenzene (HCB)', 'Arsenic and compounds (as As)', 'Total nitrogen', 'Trichlorobenzenes (TCB)', 'Tetrachloroethylene', 'Fluoranthene', 'Chlorine and inorganic compounds (as HCl)', 'Lead and compounds (as Pb)', 'Total organic carbon(as total C or COD/3) (TOC)', 'Lindane', 'Polycyclic aromatic hydrocarbons (PAHs)', 'Fluorides (as total F)', 'Particulate matter (PM10)', 'Benzo(g,h,i)perylene', 'Toluene', 'Benzene', 'Sulphur oxides (SOX)', 'Phenols (as total C)', 'Pentachlorobenzene', 'Zinc and compounds (as Zn)', 'Vinyl chloride', 'Ethyl benzene', '1,1,1-trichloroethane (TCE-1,1,1)', 'Trichloromethane', 'Aldrin', 'Ammonia (NH3)', 'Endrin', 'Dichloromethane (DCM)', 'Nitrogen oxides (NOX)', 'Chlordecone', 'Naphthalene', 'Hydrogen cyanide (HCN)', 'Chlorides (as total Cl)', 'Brominated diphenylethers (PBDE)', 'PCDD + PCDF (dioxins + furans) (as Teq)', 'Di-(2-ethyl hexyl) phthalate (DEHP)', 'Cadmium and compounds (as Cd)', 'Trichloroethylene (TRI)', 'Copper and compounds (as Cu)', 'Xylenes'}

56

In [18]:
all_pollutants = sorted(list(water_set | air_set))

In [19]:
class_sheet = pd.DataFrame(all_pollutants, columns=['name'])

In [20]:
# Classify medium presence
def determine_medium_list(pollutant):
    in_water = pollutant in water_set
    in_air = pollutant in air_set
    return pd.Series({'to_water': in_water, 'to_air': in_air})
    
    # if in_water and in_air:
    #     return 'both'
    # elif in_water:
    #     return 'water'
    # else:
    #     return 'air'

In [21]:
#class_sheet['medium'] = class_sheet['name'].apply(determine_medium_list)

class_sheet[['to_water', 'to_air']] = class_sheet['name'].apply(determine_medium_list)

In [22]:
def classify_by_parentheses(name):
    """Check if the name ends with (ABC) pattern"""
    # Match any characters ending with (content) at the end of string
    if re.search(r'\([^)]+\)$', str(name)):
        return 'group'
    else:
        return 'single'

class_sheet['type'] = class_sheet['name'].apply(classify_by_parentheses)

class_sheet.head(2)

                                                name  to_water  to_air   type
0                  1,1,1-trichloroethane (TCE-1,1,1)      True    True  group
1  1,1,2,2-tetrachloroethane (TETRACHLOROETHANE-1...      True    True  group

In [23]:
print(f"Number of pollutants reported to air: {len(class_sheet[class_sheet['to_air'] == True])}")
print(f"Number of pollutants reported to water: {len(class_sheet[class_sheet['to_water'] == True])}")
print(f"Number of pollutants reported to the E-PRTR both air & water: {len(class_sheet['name'])}")
#print(len(class_sheet[class_sheet['medium'] == 'both']))
#class_sheet.sample(7)

Number of pollutants reported to air: 69
Number of pollutants reported to water: 81
Number of pollutants reported to the E-PRTR both air & water: 94

## ! With Emipy: Cleaning & Merging Water and Air E-PRTRs !

In [24]:
pip install emipy --quiet

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [25]:
import emipy as ep

In [26]:
# ep.init_emipy_project('/home/sarah/Documents/projects/2026/Toxic Zones/eprtr_data')
# exit()

In [27]:
# db = ep.read_db()
# mb = ep.read_mb()

In [28]:
eprtr_releases = pd.concat(
    [eprtr_a, eprtr_w],
    axis=0,
    ignore_index=True,
    sort=False,
)

In [29]:
eprtr_releases.head(2)

,PublicationDate,countryName,reportingYear,EPRTR_SectorCode,EPRTR_SectorName,EPRTRAnnexIMainActivity,FacilityInspireId,facilityName,city,Longitude,Latitude,addressConfidentialityReason,TargetRelease,Pollutant,Releases,confidentialityReason
0,2026/02/13,Germany,2013,1.0,Energy sector,1(e),https://registry.gdi-de.org/id/de.nw.inspire.p...,RWE Power AG-Fabrik Fortuna Nord,Bergheim,6.65805,50.98695,NaN,AIR,Sulphur oxides (SOX),824000.0,NaN
1,2026/02/13,Sweden,2020,7.0,Intensive livestock production and aquaculture,7(a)(i),SE.CAED/10017896.Facility,Skåneägg Produktion AB,MÖRARP,12.84955,56.05316,NaN,AIR,Ammonia (NH3),16300.0,NaN

## EC & CAS Number Matching & Addition for Universal Identification

In [30]:
list(class_sheet['name'].unique())

['1,1,1-trichloroethane (TCE-1,1,1)',
 '1,1,2,2-tetrachloroethane (TETRACHLOROETHANE-1,1,2,2)',
 '1,2,3,4,5,6-hexachlorocyclohexane (HCH)',
 '1,2-dichloroethane (DCE-1,2)',
 'Alachlor',
 'Aldrin',
 'Ammonia (NH3)',
 'Anthracene',
 'Arsenic and compounds (as As)',
 'Asbestos',
 'Atrazine',
 'Benzene',
 'Benzo(g,h,i)perylene',
 'Brominated diphenylethers (PBDE)',
 'CONFIDENTIAL',
 'Cadmium and compounds (as Cd)',
 'Carbon dioxide (CO2)',
 'Carbon dioxide (CO2) excluding biomass',
 'Carbon monoxide (CO)',
 'Chlordane',
 'Chlordecone',
 'Chlorfenvinphos',
 'Chlorides (as total Cl)',
 'Chlorine and inorganic compounds (as HCl)',
 'Chloro-alkanes, C10-C13',
 'Chlorofluorocarbons (CFCs)',
 'Chlorpyrifos',
 'Chromium and compounds (as Cr)',
 'Copper and compounds (as Cu)',
 'Cyanides (as total CN)',
 'DDT (DDT)',
 'Di-(2-ethyl hexyl) phthalate (DEHP)',
 'Dichloromethane (DCM)',
 'Dieldrin',
 'Diuron',
 'Endosulphan',
 'Endrin',
 'Ethyl benzene',
 'Ethylene oxide',
 'Fine particulate matter (PM2.5)',
 'Fluoranthene',
 'Fluorides (as total F)',
 'Fluorine and inorganic compounds (as HF)',
 'Halogenated organic compounds (as AOX)',
 'Halons',
 'Heptachlor',
 'Hexabromobiphenyl',
 'Hexachlorobenzene (HCB)',
 'Hexachlorobutadiene (HCBD)',
 'Hydro-fluorocarbons (HFCS)',
 'Hydrochlorofluorocarbons (HCFCs)',
 'Hydrogen cyanide (HCN)',
 'Isodrin',
 'Isoproturon',
 'Lead and compounds (as Pb)',
 'Lindane',
 'Mercury and compounds (as Hg)',
 'Methane (CH4)',
 'Mirex',
 'Naphthalene',
 'Nickel and compounds (as Ni)',
 'Nitrogen oxides (NOX)',
 'Nitrous oxide (N2O)',
 'Non-methane volatile organic compounds (NMVOC)',
 'Nonylphenol and Nonylphenol ethoxylates',
 'Octylphenols and Octylphenol ethoxylates',
 'Organotin compounds (as total Sn)',
 'PCDD + PCDF (dioxins + furans) (as Teq)',
 'Particulate matter (PM10)',
 'Pentachlorobenzene',
 'Pentachlorophenol (PCP)',
 'Perfluorocarbons (PFCs)',
 'Phenols (as total C)',
 'Polychlorinated biphenyls (PCBs)',
 'Polycyclic aromatic hydrocarbons (PAHs)',
 'Simazine',
 'Sulphur hexafluoride (SF6)',
 'Sulphur oxides (SOX)',
 'Tetrachloroethylene',
 'Tetrachloromethane (TCM)',
 'Toluene',
 'Total nitrogen',
 'Total organic carbon(as total C or COD/3) (TOC)',
 'Total phosphorus',
 'Toxaphene',
 'Tributyltin and compounds',
 'Trichlorobenzenes (TCB)',
 'Trichloroethylene (TRI)',
 'Trichloromethane',
 'Trifluralin',
 'Triphenyltin and compounds',
 'Vinyl chloride',
 'Xylenes',
 'Zinc and compounds (as Zn)']

### Matching EC and CAS numbers as in ECHA, EC Inventory. 
#### Source link: https://echa.europa.eu/information-on-chemicals/ec-inventory

### Reported Single Substances in the E-PRTR

In [31]:
eprtr_ec_cas_dict_single = {
    '1,1,1-trichloroethane (TCE-1,1,1)': {
        'ec': '200-756-3',
        'cas': '71-55-6',
        'group': False
    },
    '1,1,2,2-tetrachloroethane (TETRACHLOROETHANE-1,1,2,2)': {
        'ec': '201-197-8',
        'cas': '79-34-5',
        'group': False 
    },
    '1,2-dichloroethane (DCE-1,2)': {
        'ec': '203-458-1',
        'cas': '107-06-2',
        'group': False 
    },
    'Alachlor': {
            'ec': '240-110-8',
            'cas': '15972-60-8',
            'group': False 
    },
    'Aldrin': {
            'ec': '206-215-8',
            'cas': '309-00-2',
            'group': False 
    },
    'Anthracene': {
            'ec': '204-371-1',
            'cas': '120-12-7',
            'group': False 
    },
    'Asbestos': {
            'ec': '',
            'cas': '1332-21-4',
            'group': False 
    },
    'Atrazine': {
            'ec':'217-617-8',
            'cas': '1912-24-9',
            'group': False
    },
    'Benzene': {
            'ec':'200-753-7',
            'cas': '71-43-2',
            'group': False
    },
    'Benzo(g,h,i)perylene': {
            'ec':'205-883-8',
            'cas': '191-24-2',
            'group': False
    },
    'Carbon dioxide (CO2)': {
            'ec':'204-696-9',
            'cas': '124-38-9',
            'group': False
    },
    'Carbon dioxide (CO2) excluding biomass': {
            'ec':'',
            'cas': '',
            'group': False
    },
    'Carbon monoxide (CO)': {
            'ec':'211-128-3',
            'cas': '630-08-0',
            'group': False
    },
    'Chlordane': {
            'ec':'200-349-0',
            'cas': '57-74-9',
            'group': False
    },
    'Chlordecone': {
            'ec':'205-601-3',
            'cas': '143-50-0',
            'group': False
    },
    'Chlorfenvinphos': {
            'ec':'207-432-0',
            'cas': '470-90-6',
            'group': False
    },
    'Chloro-alkanes, C10-C13': {
            'ec':'287-476-5',
            'cas': '85535-84-8',
            'group': False
    },
    'Chlorpyrifos': {
            'ec':'220-864-4',
            'cas': '2921-88-2',
            'group': False
    },
    'Di-(2-ethyl hexyl) phthalate (DEHP)': {
            'ec':'204-211-0',
            'cas': '117-81-7',
            'group': False
    },
    'Dichloromethane (DCM)': {
            'ec':'200-838-9',
            'cas': '75-09-2',
            'group': False
    },
    'Dieldrin': {
            'ec':'200-484-5',
            'cas': '60-57-1',
            'group': False
    },
    'Diuron': {
            'ec':'206-354-4',
            'cas': '330-54-1',
            'group': False
    },
    'Endosulphan': {
            'ec':'204-079-4',
            'cas': '115-29-7',
            'group': False
    },
    'Endrin': {
            'ec':'200-775-7',
            'cas': '72-20-8',
            'group': False
    },
    'Ethyl benzene': {
            'ec':'202-849-4',
            'cas': '100-41-4',
            'group': False
    },
    'Ethylene oxide': {
            'ec':'200-849-9',
            'cas': '75-21-8',
            'group': False
    },
    'Fluoranthene': {
            'ec':'205-912-4',
            'cas': '206-44-0',
            'group': False
    },
    'Heptachlor': {
            'ec':'200-962-3',
            'cas': '76-44-8',
            'group': False
    },
    'Hexabromobiphenyl': {
            'ec':'252-994-2',
            'cas': '36355-1-8',
            'group': False
    },
    'Hexachlorobenzene (HCB)': {
            'ec':'204-273-9',
            'cas': '118-74-1',
            'group': False
    },
    'Hexachlorobutadiene (HCBD)': {
            'ec':'201-765-5',
            'cas': '87-68-3',
            'group': False
    },
    'Hydrogen cyanide (HCN)': {
            'ec':'200-821-6',
            'cas': '74-90-8',
            'group': False
    },
    'Isodrin': {
            'ec':'207-366-2',
            'cas': '465-73-6',
            'group': False
    },
    'Isoproturon': {
            'ec':'251-835-4',
            'cas': '34123-59-6',
            'group': False
    },
    'Lindane': {
            'ec':'200-401-2',
            'cas': '58-89-9',
            'group': False
    },
    'Methane (CH4)': {
            'ec':'200-812-7',
            'cas': '74-82-8',
            'group': False
    },
    'Mirex': {
            'ec':'219-196-6',
            'cas': '2385-85-5',
            'group': False
    },
    'Naphthalene': {
            'ec':'202-049-5',
            'cas': '91-20-3',
            'group': False
    },
    'Nitrous oxide (N2O)': {
            'ec':'233-032-0',
            'cas': '10024-97-2',
            'group': False
    },
    'Octylphenols and Octylphenol ethoxylates': {
            'ec':'217-302-5',
            'cas': '1806-26-4',
            'group': False
    },
    'Pentachlorobenzene': {
            'ec':'210-172-0',
            'cas': '608-93-5',
            'group': False
    },
    'Pentachlorophenol (PCP)': {
            'ec':'201-778-6',
            'cas': '87-86-5',
            'group': False
    },
    'Phenols (as total C)': {
            'ec':'203-632-7',
            'cas': '108-95-2',
            'group': False
    },
    'Polychlorinated biphenyls (PCBs)': {
            'ec':'215-648-1',
            'cas': '1336-36-3',
            'group': False
    },
    'Simazine': {
            'ec':'204-535-2',
            'cas': '122-34-9',
            'group': False
    },
    'Sulphur hexafluoride (SF6)': {
            'ec':'219-854-2',
            'cas': '2551-62-4',
            'group': False
    },
    'Tetrachloroethylene': {
            'ec':'204-825-9',
            'cas': '127-18-4',
            'group': False
    },
    'Tetrachloromethane (TCM)': {
            'ec':'200-262-8',
            'cas': '56-23-5',
            'group': False
    },
    'Toluene': {
            'ec':'203-625-9',
            'cas': '108-88-3',
            'group': False
    },
    'Toxaphene': {
            'ec':'232-283-3',
            'cas': '8001-35-2',
            'group': False
    },
    'Trichlorobenzenes (TCB)': {
            'ec':'234-413-4',
            'cas': '12002-48-1',
            'group': False
    },
    'Trichloroethylene (TRI)': {
            'ec':'201-167-4',
            'cas': '79-01-6',
            'group': False
    },
    'Trichloromethane': {
            'ec':'200-663-8',
            'cas': '67-66-3',
            'group': False
    },
    'Trifluralin': {
            'ec':'216-428-8',
            'cas': '1582-09-8',
            'group': False
    },
    'Vinyl chloride': {
            'ec':'200-831-0',
            'cas': '75-01-4',
            'group': False
    },
    'Xylenes': {
            'ec':'215-535-7',
            'cas': '1330-20-7',
            'group': False
    }
}

## Adding EC and CAS for Single Substances to the EPRTR

In [32]:
cas_ec_class = (
    pd.DataFrame.from_dict(
        eprtr_ec_cas_dict_single,
        orient="index"
    )
    .rename_axis("pollutant")
    .reset_index()
)

In [33]:
cas_ec_class.head()

,pollutant,ec,cas,group
0,"1,1,1-trichloroethane (TCE-1,1,1)",200-756-3,71-55-6,False
1,"1,1,2,2-tetrachloroethane (TETRACHLOROETHANE-1...",201-197-8,79-34-5,False
2,"1,2-dichloroethane (DCE-1,2)",203-458-1,107-06-2,False
3,Alachlor,240-110-8,15972-60-8,False
4,Aldrin,206-215-8,309-00-2,False

In [34]:
eprtr_releases_with_cas = eprtr_releases.merge(
    cas_ec_class[
        ["pollutant", "ec", "cas", "group"]
    ],
    how="left",
    left_on="Pollutant",
    right_on="pollutant",
    validate="many_to_one",
    indicator=False,
)

#### Adding Boolean Identifier for pollutants, column 'group': True - False, Substance Group - Single Substance

In [35]:
eprtr_releases_with_cas = (
    eprtr_releases_with_cas
    .drop(columns="pollutant")
    .assign(
        group=lambda df: (
            df["group"]
            .fillna(True)
            .astype(bool)
        )
    )
)

/tmp/ipykernel_221216/1519720469.py:7: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .fillna(True)

In [36]:
eprtr_releases_with_cas.head(5)

,PublicationDate,countryName,reportingYear,EPRTR_SectorCode,EPRTR_SectorName,EPRTRAnnexIMainActivity,FacilityInspireId,facilityName,city,Longitude,Latitude,addressConfidentialityReason,TargetRelease,Pollutant,Releases,confidentialityReason,ec,cas,group
0,2026/02/13,Germany,2013,1.0,Energy sector,1(e),https://registry.gdi-de.org/id/de.nw.inspire.p...,RWE Power AG-Fabrik Fortuna Nord,Bergheim,6.658050,50.986950,NaN,AIR,Sulphur oxides (SOX),824000.0,NaN,NaN,NaN,True
1,2026/02/13,Sweden,2020,7.0,Intensive livestock production and aquaculture,7(a)(i),SE.CAED/10017896.Facility,Skåneägg Produktion AB,MÖRARP,12.849550,56.053160,NaN,AIR,Ammonia (NH3),16300.0,NaN,NaN,NaN,True
2,2026/02/13,Romania,2013,5.0,Waste and wastewater management,5(d),RO.CAED/104TL0001.FACILITY,SC ECOREC SA,TULCEA,28.769671,45.190459,NaN,AIR,Methane (CH4),269000.0,NaN,200-812-7,74-82-8,False
3,2026/02/13,Italy,2021,7.0,Intensive livestock production and aquaculture,7(a),IT.CAED/370602036.FACILITY,RONCHETRIN 1,GAZZO VERONESE,11.106667,45.123611,NaN,AIR,Ammonia (NH3),31920.0,NaN,NaN,NaN,True
4,2026/02/13,Czechia,2007,1.0,Energy sector,1(c),CZ.MZP.U423/CZ14819275.FACILITY,energetika,Štětí,14.380370,50.462296,NaN,AIR,Sulphur oxides (SOX),507000.0,NaN,NaN,NaN,True

### Reported Substance Groups in the EPRTR

In [37]:
eprtr_ec_cas_dict_group = {
    '1,2,3,4,5,6-hexachlorocyclohexane (HCH)': {
        'group': True,
        'entries': [
            {'name': '(1α,2α,3α,4β,5α,6β)-1,2,3,4,5,6-hexachlorocyclohexane', 'ec': '206-272-9', 'cas': '319-86-8'},
            {'name': '(1α,2α,3α,4β,5β,6β)-1,2,3,4,5,6-hexachlorocyclohexane', 'ec': '228-068-9', 'cas': '6108-10-7'},
            {'name': '(1α,2α,3β,4α,5β,6β)-1,2,3,4,5,6-hexachlorocyclohexane', 'ec': '206-270-8', 'cas': '319-84-6'},
            {'name': '(1α,2β,3α,4β,5α,6β)-1,2,3,4,5,6-hexachlorocyclohexane', 'ec': '206-271-3', 'cas': '319-85-7'}
        ]
    }
    'Ammonia (NH3)': {
        'group': True,
        'entries': [
            {'name': '(2H3)ammonia', 'ec': '236-926-9', 'cas': '13550-49-7'},
            {'name': '1,3,5-Triazine-2,4,6(1H,3H,5H)-trione, manuf. of, nitric acid purified, ammonia neutralized, by-products from', 'ec': '292-292-3', 'cas': '90583-88-3'},
            {}
        ]
    }
    'Arsenic and compounds (as As)': {
        'group': True,
        'entries': []
    }
    'Brominated diphenylethers (PBDE)': {
        'group': True,
        'entries': [
            {'name': '', 'ec': '', 'cas': ''},
            {'name': '', 'ec': '', 'cas': ''}
        ]
    }
    'Cadmium and compounds (as Cd)': {
        'group': True,
        'entries': [
            {'name': '', 'ec': '', 'cas': ''}
        ]
    }
    'Chlorides (as total Cl)': {
        'group': True,
        'entries': [
            {'name': '', 'ec': '', 'cas': ''}
        ]
    }
    'Chlorine and inorganic compounds (as HCl)': {
        'group': True,
        'entries': [
            {'name': '', 'ec': '', 'cas': ''}
        ]
    }
    'Chlorofluorocarbons (CFCs)': {
        'group': True,
        'entries': [
            {'name': '', 'ec': '', 'cas': ''}
        ]
    }
    'Chromium and compounds (as Cr)': {
        'group': True,
        'entries': [
            {'name': '', 'ec': '', 'cas': ''}
        ]
    }
    'Copper and compounds (as Cu)': {
        'group': True,
        'entries': [
            {'name': '', 'ec': '', 'cas': ''}
        ]
    }
    'Cyanides (as total CN)': {
        'group': True,
        'entries': [
            {'name': '', 'ec': '', 'cas': ''}
        ]
    }
    'Fine particulate matter (PM2.5)': {
        'group': True,
        'entries': [
            {'name': '', 'ec': '', 'cas': ''}
        ]
    }
    'Fluorides (as total F)': {
        'group': True,
        'entries': [
            {'name': '', 'ec': '', 'cas': ''}
        ]
    }
    'Fluorine and inorganic compounds (as HF)': {
        'group': True,
        'entries': [
            {'name': '', 'ec': '', 'cas': ''}
        ]
    }
    'Halogenated organic compounds (as AOX)': {
        'group': True,
        'entries': [
            {'name': '', 'ec': '', 'cas': ''}
        ]
    }
    'Halons': {
        'group': True,
        'entries': [
            {'name': '', 'ec': '', 'cas': ''}
        ]
    }
    'Hydro-fluorocarbons (HFCS)': {
        'group': True,
        'entries': [
            {'name': '', 'ec': '', 'cas': ''}
        ]
    }
    'Hydrochlorofluorocarbons (HCFCs)': {
        'group': True,
        'entries': [
            {'name': '', 'ec': '', 'cas': ''}
        ]
    }
    'Lead and compounds (as Pb)': {
        'group': True,
        'entries': [
            {'name': '', 'ec': '', 'cas': ''}
        ]
    }
    'Mercury and compounds (as Hg)': {
        'group': True,
        'entries': [
            {'name': '', 'ec': '', 'cas': ''}
        ]
    }
    'Nickel and compounds (as Ni)': {
        'group': True,
        'entries': [
            {'name': '', 'ec': '', 'cas': ''}
        ]
    }
    'Nitrogen oxides (NOX)': {
        'group': True,
        'entries': [
            {'name': '', 'ec': '', 'cas': ''}
        ]
    }
    'Non-methane volatile organic compounds (NMVOC)': {
        'group': True,
        'entries': [
            {'name': '', 'ec': '', 'cas': ''}
        ]
    }
    'Nonylphenol and Nonylphenol ethoxylates': {
        'group': True,
        'entries': [
            {'name': '', 'ec': '', 'cas': ''}
        ]
    }
    'Organotin compounds (as total Sn)': {
        'group': True,
        'entries': [
            {'name': '', 'ec': '', 'cas': ''}
        ]
    }
    'PCDD + PCDF (dioxins + furans) (as Teq)': {
        'group': True,
        'entries': [
            {'name': '', 'ec': '', 'cas': ''}
        ]
    }
    'Particulate matter (PM10)': {
        'group': True,
        'entries': [
            {'name': '', 'ec': '', 'cas': ''}
        ]
    }
    'Perfluorocarbons (PFCs)': {
        'group': True,
        'entries': [
            {'name': '', 'ec': '', 'cas': ''}
        ]
    }
    'Polycyclic aromatic hydrocarbons (PAHs)': {
        'group': True,
        'entries': [
            {'name': '', 'ec': '', 'cas': ''}
        ]
    }
     'Sulphur oxides (SOX)': {
        'group': True,
        'entries': [
            {'name': '', 'ec': '', 'cas': ''}
        ]
    }
     'Total nitrogen': {
        'group': True,
        'entries': [
            {'name': '', 'ec': '', 'cas': ''}
        ]
    }
     'Total organic carbon(as total C or COD/3) (TOC)': {
        'group': True,
        'entries': [
            {'name': '', 'ec': '', 'cas': ''}
        ]
    }
     'Total phosphorus': {
        'group': True,
        'entries': [
            {'name': '', 'ec': '', 'cas': ''}
        ]
    }
     'Tributyltin and compounds': {
        'group': True,
        'entries': [
            {'name': '', 'ec': '', 'cas': ''}
        ]
    }
     'Triphenyltin and compounds': {
        'group': True,
        'entries': [
            {'name': '', 'ec': '', 'cas': ''}
        ]
    }
     'Zinc and compounds (as Zn)': {
        'group': True,
        'entries': [
            {'name': '', 'ec': '', 'cas': ''}
        ]
    }

}

SyntaxError: invalid syntax. Perhaps you forgot a comma? (2317262212.py, line 2)

## Adding reporting thresholds from EPRTR legislative text, Annex II 'Pollutants'

In [38]:
eprtr_reporting = pd.read_excel("/home/sarah/Documents/projects/2026/Toxic Zones/data/eprtr_lex_list.xlsx")

In [39]:
eprtr_reporting.head(5)

,No,CAS number,Pollutant (1),threshold_air_kg/year,threshold_water_kg/year,threshold_land_kg/year
0,1,74-82-8,Methane (CH4),100 000,— (2),—
1,2,630-08-0,Carbon monoxide (CO),500 000,—,—
2,3,124-38-9,Carbon dioxide (CO2),100 million,—,—
3,4,,Hydro-fluorocarbons (HFCs) (3),100,—,—
4,5,10024-97-2,Nitrous oxide (N2O),10 000,—,—

In [40]:
eprtr_releases_with_thresh = eprtr_releases_with_cas.merge(
    eprtr_reporting[
        ["No", "CAS number", "Pollutant (1)", "threshold_air_kg/year", "threshold_water_kg/year", "threshold_land_kg/year"]
    ],
    how="left",
    left_on="Pollutant",
    right_on="Pollutant (1)",
    validate="many_to_one",
    indicator=False,
)

In [41]:
eprtr_releases_with_thresh = (
    eprtr_releases_with_thresh
    .drop(columns=["No","Pollutant (1)","cas"])
    .rename(columns={"CAS number": "cas"})
)

In [42]:
eprtr_releases_with_thresh.head(5)

,PublicationDate,countryName,reportingYear,EPRTR_SectorCode,EPRTR_SectorName,EPRTRAnnexIMainActivity,FacilityInspireId,facilityName,city,Longitude,...,TargetRelease,Pollutant,Releases,confidentialityReason,ec,group,cas,threshold_air_kg/year,threshold_water_kg/year,threshold_land_kg/year
0,2026/02/13,Germany,2013,1.0,Energy sector,1(e),https://registry.gdi-de.org/id/de.nw.inspire.p...,RWE Power AG-Fabrik Fortuna Nord,Bergheim,6.658050,...,AIR,Sulphur oxides (SOX),824000.0,NaN,NaN,True,NaN,NaN,NaN,NaN
1,2026/02/13,Sweden,2020,7.0,Intensive livestock production and aquaculture,7(a)(i),SE.CAED/10017896.Facility,Skåneägg Produktion AB,MÖRARP,12.849550,...,AIR,Ammonia (NH3),16300.0,NaN,NaN,True,7664-41-7,10 000,—,—
2,2026/02/13,Romania,2013,5.0,Waste and wastewater management,5(d),RO.CAED/104TL0001.FACILITY,SC ECOREC SA,TULCEA,28.769671,...,AIR,Methane (CH4),269000.0,NaN,200-812-7,False,74-82-8,100 000,— (2),—
3,2026/02/13,Italy,2021,7.0,Intensive livestock production and aquaculture,7(a),IT.CAED/370602036.FACILITY,RONCHETRIN 1,GAZZO VERONESE,11.106667,...,AIR,Ammonia (NH3),31920.0,NaN,NaN,True,7664-41-7,10 000,—,—
4,2026/02/13,Czechia,2007,1.0,Energy sector,1(c),CZ.MZP.U423/CZ14819275.FACILITY,energetika,Štětí,14.380370,...,AIR,Sulphur oxides (SOX),507000.0,NaN,NaN,True,NaN,NaN,NaN,NaN

In [43]:
eprtr_releases_with_thresh.columns

Index(['PublicationDate', 'countryName', 'reportingYear', 'EPRTR_SectorCode',
       'EPRTR_SectorName', 'EPRTRAnnexIMainActivity', 'FacilityInspireId',
       'facilityName', 'city', 'Longitude', 'Latitude',
       'addressConfidentialityReason', 'TargetRelease', 'Pollutant',
       'Releases', 'confidentialityReason', 'ec', 'group', 'cas',
       'threshold_air_kg/year', 'threshold_water_kg/year',
       'threshold_land_kg/year'],
      dtype='object')

## Official Classification by Lists

### EPA Hazardous Air Pollutants
##### Official classification list, source: https://www.epa.gov/haps/initial-list-hazardous-air-pollutants-modifications

In [44]:
hap = pd.read_excel("/home/sarah/Documents/projects/2026/Toxic Zones/official_classifications/epa_hap_list.xlsx", sheet_name = 'hap_table')
hap.head(5)
#hap.info()
hap.columns

Index(['CAS Number', 'Chemical Name'], dtype='object')

### IARC Monographs
##### Official classification list, source: https://monographs.iarc.who.int/list-of-classifications/

In [45]:
iarc = pd.read_excel("/home/sarah/Documents/projects/2026/Toxic Zones/official_classifications/Agents Classified by the IARC Monographs, Volumes 1–142.xlsx", skiprows = 1)
iarc.head(5)
iarc.columns

Index(['CAS No.', 'Agent', 'Group', 'Volume', 'Volume publication year',
       'Evaluation year', 'Additional information'],
      dtype='object')

### CLP Harmonised List
##### Official classification list, source: https://chem.echa.europa.eu/obligation-lists/clhList

In [46]:
clp = pd.read_excel("/home/sarah/Documents/projects/2026/Toxic Zones/official_classifications/Harmonised_List_2026-10-03 11_18_19.xlsx")
clp.head(5)
#clp.columns

/home/sarah/.config/jupyterlab-desktop/jlab_server/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,Substance name,EC number,CAS number,Index number,"Hazard class, category and statement code(s)",ATP,From,To
0,hydrogen,215-605-7,1333-74-0,001-001-00-9,"Flam. Gas 1, H220\nPress. Gas",CLP00,01-Dec-2010,-
1,aluminium lithium hydride,240-877-9,16853-85-3,001-002-00-4,"Water-react. 1, H260\nSkin Corr. 1A, H314",ATP01,01-Dec-2010,-
2,sodium hydride,231-587-3,7646-69-7,001-003-00-X,"Water-react. 1, H260",CLP00,01-Dec-2010,-
3,calcium hydride,232-189-2,7789-78-8,001-004-00-5,"Water-react. 1, H260",CLP00,01-Dec-2010,-
4,lithium,231-102-5,7439-93-2,003-001-00-4,"Water-react. 1, H260\nSkin Corr. 1B, H314",CLP00,01-Dec-2010,-

### REACH Candidate List of substances of very high concern
##### Official classification list, source: https://chem.echa.europa.eu/obligation-lists/candidateList

In [47]:
cand_svhc = pd.read_excel("/home/sarah/Documents/projects/2026/Toxic Zones/official_classifications/candidate_list_full-2026-10-02.xlsx")
cand_svhc.head(5)
cand_svhc.columns

/home/sarah/.config/jupyterlab-desktop/jlab_server/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

Index(['Substance name', 'Description', 'EC number', 'CAS number',
       'Date of inclusion', 'Reason for inclusion', 'Decision',
       'Regulatory outcome', 'Regulatory outcome date'],
      dtype='object')

### WFD Priority Substances
##### Official classification list, source: https://echa.europa.eu/ann-x-priority-subs-water-dir-2000-60?p_p_id=eucleflegislationlist_WAR_euclefportlet&p_p_lifecycle=0&p_p_state=normal&p_p_mode=view&_eucleflegislationlist_WAR_euclefportlet_orderByCol=rmlName&_eucleflegislationlist_WAR_euclefportlet_substance_identifier_field_key=&_eucleflegislationlist_WAR_euclefportlet_orderByType=asc&_eucleflegislationlist_WAR_euclefportlet_doSearch=&_eucleflegislationlist_WAR_euclefportlet_deltaParamValue=50&_eucleflegislationlist_WAR_euclefportlet_resetCur=false&_eucleflegislationlist_WAR_euclefportlet_delta=50&_eucleflegislationlist_WAR_euclefportlet_cur=2

In [48]:
wfd_prio = pd.read_excel("/home/sarah/Documents/projects/2026/Toxic Zones/official_classifications/water-framework-directive-annex-x-priority-substances-export.xlsx", skiprows = 4)
wfd_prio.head(5)
wfd_prio.columns

/home/sarah/.config/jupyterlab-desktop/jlab_server/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

Index(['Substance Name', 'EC No.', 'CAS No.', 'Name', 'EC Number', 'CAS',
       'Priority', 'Group', 'Notes'],
      dtype='object')

## Availability in USEtox

In [85]:
usetox_list = pd.read_excel("/home/sarah/Documents/projects/2026/Toxic Zones/usetox_eprtr/ied_eprtr_usetox.xlsx")
usetox_list.head(5)

/home/sarah/.config/jupyterlab-desktop/jlab_server/lib/python3.12/site-packages/openpyxl/worksheet/_reader.py:223: UserWarning: Cell A91 is marked as a date but the serial value 12584439.0 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)

      cas_num                       pollutant usetox note
0     74-82-8                   Methane (CH4)    yes  NaN
1    630-08-0            Carbon monoxide (CO)     no  NaN
2    124-38-9            Carbon dioxide (CO2)     no  NaN
3         NaN  Hydro-fluorocarbons (HFCs) (3)     no  NaN
4  10024-97-2             Nitrous oxide (N2O)     no  NaN

In [86]:
in_usetox = usetox_list[usetox_list["usetox"] == "yes"]
in_usetox

       cas_num                                 pollutant usetox note
0      74-82-8                             Methane (CH4)    yes  NaN
24  15972-60-8                                  Alachlor    yes  NaN
25    309-00-2                                    Aldrin    yes  NaN
26   1912-24-9                                  Atrazine    yes  NaN
27     57-74-9                                 Chlordane    yes  NaN
28    143-50-0                               Chlordecone    yes  NaN
29    470-90-6                           Chlorfenvinphos    yes  NaN
30  85535-84-8                   Chloro-alkanes, C10-C13    yes  NaN
31   2921-88-2                              Chlorpyrifos    yes  NaN
32     50-29-3                                       DDT    yes  NaN
34     75-09-2                     Dichloromethane (DCM)    yes  NaN
35     60-57-1                                  Dieldrin    yes  NaN
36    330-54-1                                    Diuron    yes  NaN
37    115-29-7                               Endosulphan    yes  NaN
38     72-20-8                                    Endrin    yes  NaN
40     76-44-8                                Heptachlor    yes  NaN
41    118-74-1                   Hexachlorobenzene (HCB)    yes  NaN
42     87-68-3                Hexachlorobutadiene (HCBD)    yes  NaN
43    608-73-1    1,2,3,4,5,6-hexachlorocyclohexane(HCH)    yes  NaN
44     58-89-9                                   Lindane    yes  NaN
45   2385-85-5                                     Mirex    yes  NaN
47    608-93-5                        Pentachlorobenzene    yes  NaN
48     87-86-5                   Pentachlorophenol (PCP)    yes  NaN
50    122-34-9                                  Simazine    yes  NaN
51    127-18-4                 Tetrachloroethylene (PER)    yes  NaN
52     56-23-5                  Tetrachloromethane (TCM)    yes  NaN
53  12002-48-1    Trichlorobenzenes (TCBs) (all isomers)    yes  NaN
54     71-55-6                     1,1,1-trichloroethane    yes  NaN
55     79-34-5                 1,1,2,2-tetrachloroethane    yes  NaN
56     79-01-6                         Trichloroethylene    yes  NaN
59     75-01-4                            Vinyl chloride    yes  NaN
61     71-43-2                                   Benzene    yes  NaN
64    100-41-4                             Ethyl benzene    yes  NaN
65     75-21-8                            Ethylene oxide    yes  NaN
66  34123-59-6                               Isoproturon    yes  NaN
67     91-20-3                               Naphthalene    yes  NaN
69    117-81-7       Di-(2-ethyl hexyl) phthalate (DEHP)    yes  NaN
70    108-95-2                 Phenols (as total C) (13)    yes  NaN
72    108-88-3                                   Toluene    yes  NaN
86   1806-26-4  Octylphenols and Octylphenol ethoxylates    yes  NaN
87    206-44-0                              Fluoranthene    yes  NaN
90    191-24-2                      Benzo(g,h,i)perylene    yes  NaN

## Assigning classification tags to all reported, released pollutants

In [88]:
eprtr_classified = eprtr_releases_with_thresh.copy()

# Boolean flags
eprtr_classified["hap"] = eprtr_classified["cas"].isin(hap["CAS Number"])

eprtr_classified["cand_svhc"] = eprtr_classified["cas"].isin(
    cand_svhc["CAS number"]
)

eprtr_classified["wfd_prio_sub"] = eprtr_classified["cas"].isin(
    wfd_prio["CAS No."]
) | eprtr_classified["cas"].isin(
    wfd_prio["CAS"]
)

eprtr_classified["usetox"] = eprtr_classified["cas"].isin(
    in_usetox["cas_num"]
)


# IARC: CAS → IARC cancer group
iarc_map = (
    iarc
    .drop_duplicates(subset="CAS No.")
    .set_index("CAS No.")["Group"]
)

eprtr_classified["iarc_group"] = eprtr_classified["cas"].map(iarc_map)

# CLP: CAS → harmonised classification / hazard statements
clp_map = (
    clp
    .drop_duplicates(subset="CAS number")
    .set_index("CAS number")[
        "Hazard class, category and statement code(s)"
    ]
)


eprtr_classified["clp_class"] = eprtr_classified["cas"].map(clp_map)

In [89]:
eprtr_classified

,PublicationDate,countryName,reportingYear,EPRTR_SectorCode,EPRTR_SectorName,EPRTRAnnexIMainActivity,FacilityInspireId,facilityName,city,Longitude,...,cas,threshold_air_kg/year,threshold_water_kg/year,threshold_land_kg/year,hap,cand_svhc,wfd_prio_sub,usetox,iarc_group,clp_class
0,2026/02/13,Germany,2013,1.0,Energy sector,1(e),https://registry.gdi-de.org/id/de.nw.inspire.p...,RWE Power AG-Fabrik Fortuna Nord,Bergheim,6.658050,...,NaN,NaN,NaN,NaN,False,False,True,False,2B,NaN
1,2026/02/13,Sweden,2020,7.0,Intensive livestock production and aquaculture,7(a)(i),SE.CAED/10017896.Facility,Skåneägg Produktion AB,MÖRARP,12.849550,...,7664-41-7,10 000,—,—,False,False,False,False,NaN,"Flam. Gas 2, H221\nPress. Gas\nAcute Tox. 3*, ..."
2,2026/02/13,Romania,2013,5.0,Waste and wastewater management,5(d),RO.CAED/104TL0001.FACILITY,SC ECOREC SA,TULCEA,28.769671,...,74-82-8,100 000,— (2),—,False,False,False,True,NaN,"Flam. Gas 1, H220\nPress. Gas"
3,2026/02/13,Italy,2021,7.0,Intensive livestock production and aquaculture,7(a),IT.CAED/370602036.FACILITY,RONCHETRIN 1,GAZZO VERONESE,11.106667,...,7664-41-7,10 000,—,—,False,False,False,False,NaN,"Flam. Gas 2, H221\nPress. Gas\nAcute Tox. 3*, ..."
4,2026/02/13,Czechia,2007,1.0,Energy sector,1(c),CZ.MZP.U423/CZ14819275.FACILITY,energetika,Štětí,14.380370,...,NaN,NaN,NaN,NaN,False,False,True,False,2B,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
626357,2026/02/13,Norway,2008,7.0,Intensive livestock production and aquaculture,7(b),NO.EEA/1547.0030.02.FACILITY,"Aukrasanden, matfisk",Bergen,6.926050,...,NaN,NaN,NaN,NaN,False,False,True,False,2B,NaN
626358,2026/02/13,Netherlands,2018,5.0,Waste and wastewater management,5(c),NL.RIVM/000114740.FACILITY,RWZI Susteren,Susteren,5.833590,...,NaN,NaN,NaN,NaN,False,False,True,False,2B,NaN
626359,2026/02/13,United Kingdom,2014,1.0,Energy sector,1(c),UK.CAED/BEISOffsh-Clyde.FACILITY,Clyde Alpha,--,2.288330,...,NaN,NaN,NaN,NaN,False,False,True,False,2B,NaN
626360,2026/02/13,Spain,2021,5.0,Waste and wastewater management,5(f),ES.CAED/007766000.FACILITY,EDAR LA LLAGOSTA,"Llagosta, La",2.202064,...,NaN,NaN,NaN,NaN,False,False,True,False,2B,NaN
626361,2026/02/13,Germany,2024,5.0,Waste and wastewater management,5(f),https://registry.gdi-de.org/id/de.bw.lubw.insp...,SKA Heilbronn,Heilbronn,9.216570,...,NaN,NaN,NaN,NaN,False,False,True,False,2B,NaN

In [91]:
eprtr_classified.columns

Index(['PublicationDate', 'countryName', 'reportingYear', 'EPRTR_SectorCode',
       'EPRTR_SectorName', 'EPRTRAnnexIMainActivity', 'FacilityInspireId',
       'facilityName', 'city', 'Longitude', 'Latitude',
       'addressConfidentialityReason', 'TargetRelease', 'Pollutant',
       'Releases', 'confidentialityReason', 'ec', 'group', 'cas',
       'threshold_air_kg/year', 'threshold_water_kg/year',
       'threshold_land_kg/year', 'hap', 'cand_svhc', 'wfd_prio_sub', 'usetox',
       'iarc_group', 'clp_class'],
      dtype='object')

In [92]:
classification_columns = ["hap", "cand_svhc", "wfd_prio_sub", "iarc_group", "clp_class"]

classified_releases = eprtr_classified.loc[
    eprtr_classified[classification_columns]
    .eq(True)
    .fillna(False)
    .any(axis=1)
].copy()

In [93]:
classified_releases

,PublicationDate,countryName,reportingYear,EPRTR_SectorCode,EPRTR_SectorName,EPRTRAnnexIMainActivity,FacilityInspireId,facilityName,city,Longitude,...,cas,threshold_air_kg/year,threshold_water_kg/year,threshold_land_kg/year,hap,cand_svhc,wfd_prio_sub,usetox,iarc_group,clp_class
0,2026/02/13,Germany,2013,1.0,Energy sector,1(e),https://registry.gdi-de.org/id/de.nw.inspire.p...,RWE Power AG-Fabrik Fortuna Nord,Bergheim,6.658050,...,NaN,NaN,NaN,NaN,False,False,True,False,2B,NaN
4,2026/02/13,Czechia,2007,1.0,Energy sector,1(c),CZ.MZP.U423/CZ14819275.FACILITY,energetika,Štětí,14.380370,...,NaN,NaN,NaN,NaN,False,False,True,False,2B,NaN
5,2026/02/13,Spain,2016,1.0,Energy sector,1(a),ES.CAED/003701000.FACILITY,"PETROLEOS DEL NORTE, PETRONOR, S.A. (PETRONOR)",Muskiz,-3.110944,...,NaN,NaN,NaN,NaN,False,False,True,False,2B,NaN
8,2026/02/13,Spain,2021,1.0,Energy sector,1(c),ES.CAED/003528000.FACILITY,ENERGYWORKS VILLARROBLEDO S.L.,VILLARROBLEDO,-2.590900,...,NaN,NaN,NaN,NaN,False,False,True,False,2B,NaN
9,2026/02/13,France,2010,1.0,Energy sector,1(a),FR.CAED/5422.FACILITY,TOTALENERGIES RAFFINAGE FRANCE,FEYZIN,4.861130,...,NaN,NaN,NaN,NaN,False,False,True,False,2B,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
626357,2026/02/13,Norway,2008,7.0,Intensive livestock production and aquaculture,7(b),NO.EEA/1547.0030.02.FACILITY,"Aukrasanden, matfisk",Bergen,6.926050,...,NaN,NaN,NaN,NaN,False,False,True,False,2B,NaN
626358,2026/02/13,Netherlands,2018,5.0,Waste and wastewater management,5(c),NL.RIVM/000114740.FACILITY,RWZI Susteren,Susteren,5.833590,...,NaN,NaN,NaN,NaN,False,False,True,False,2B,NaN
626359,2026/02/13,United Kingdom,2014,1.0,Energy sector,1(c),UK.CAED/BEISOffsh-Clyde.FACILITY,Clyde Alpha,--,2.288330,...,NaN,NaN,NaN,NaN,False,False,True,False,2B,NaN
626360,2026/02/13,Spain,2021,5.0,Waste and wastewater management,5(f),ES.CAED/007766000.FACILITY,EDAR LA LLAGOSTA,"Llagosta, La",2.202064,...,NaN,NaN,NaN,NaN,False,False,True,False,2B,NaN
626361,2026/02/13,Germany,2024,5.0,Waste and wastewater management,5(f),https://registry.gdi-de.org/id/de.bw.lubw.insp...,SKA Heilbronn,Heilbronn,9.216570,...,NaN,NaN,NaN,NaN,False,False,True,False,2B,NaN

## Enriching E-PRTR by facility details and documents

In [94]:
ied_instal = pd.read_csv("/home/sarah/Documents/projects/2026/Toxic Zones/eprtr_data/eea_t_ied-eprtr_p_2007-2024_v16_r00/User friendly .csv files/F6_1_IED_Installations.csv")
ied_instal.head(5)
ied_instal.columns

Index(['PublicationDate', 'CountryName', 'reportingYear',
       'parent_facilityInspireId', 'EPRTRAnnexIMainActivity',
       'InstallationInspireId', 'installationName',
       'installationNameConfidentialityReason', 'City_of_Facility',
       'Longitude', 'Latitude', 'addressConfidentialityReason',
       'installationStatus', 'IEDAnnexIMainActivity', 'IEDMainActivityName',
       'baselineReportIndicator', 'siteVisitNumber', 'siteVisitURL',
       'dateOfStartOfOperation', 'publicEmissionMonitoring',
       'publicEmissionMonitoringURL', 'permitGranted', 'dateOfGranting',
       'permitReconsidered', 'permitUpdated', 'dateOfLastUpdate', 'permitURL',
       'RelevantChapter', 'BATConclusion', 'BATAEL',
       'BATAELStricterCondition'],
      dtype='object')

In [95]:
ied_instal.tail(5)

,PublicationDate,CountryName,reportingYear,parent_facilityInspireId,EPRTRAnnexIMainActivity,InstallationInspireId,installationName,installationNameConfidentialityReason,City_of_Facility,Longitude,...,permitGranted,dateOfGranting,permitReconsidered,permitUpdated,dateOfLastUpdate,permitURL,RelevantChapter,BATConclusion,BATAEL,BATAELStricterCondition
477639,2026/02/13,Germany,2023,https://registry.gdi-de.org/id/de.bw.lubw.insp...,5(a),https://registry.gdi-de.org/id/de.bw.lubw.insp...,Altholzlager AIV (gef. Abfall),NaN,Villingen-Schwenningen,8.55814,...,No,1900-01-01,No,No,1900-01-01,NaN,NaN,WT,NaN,NaN
477640,2026/02/13,Germany,2023,https://registry.gdi-de.org/id/de.bw.lubw.insp...,5(a),https://registry.gdi-de.org/id/de.bw.lubw.insp...,"zeitw. Lagerung, gef. Abfall >= 50 t",NaN,Göppingen,9.69005,...,Yes,1900-01-01,No,No,1900-01-01,https://rp.baden-wuerttemberg.de/rps/Service/B...,NaN,WT,NaN,NaN
477641,2026/02/13,Germany,2023,https://registry.gdi-de.org/id/de.bw.lubw.insp...,6(b),https://registry.gdi-de.org/id/de.bw.lubw.insp...,"Herst. von Papier, Karton, Pappe >= 20 t/d",NaN,Kehl,7.81762,...,Yes,1900-01-01,Yes,No,2022-03-08,https://rp.baden-wuerttemberg.de/rpf/service/b...,NaN,PP,NaN,NaN
477642,2026/02/13,Germany,2023,https://registry.gdi-de.org/id/de.bw.lubw.insp...,5(a),https://registry.gdi-de.org/id/de.bw.lubw.insp...,Beseitigung/Verwertung von gefährlichen Abfäll...,NaN,Krautheim,9.63082,...,Yes,1900-01-01,No,No,1900-01-01,https://rp.baden-wuerttemberg.de/rps/Service/B...,NaN,WT,NaN,NaN
477643,2026/02/13,Germany,2023,https://registry.gdi-de.org/id/de.bw.lubw.insp...,6(c),https://registry.gdi-de.org/id/de.bw.lubw.insp...,Konservierung von Holz/Holzerzeugnissen mit Ch...,NaN,Hüfingen,8.48949,...,Yes,1900-01-01,No,No,1900-01-01,https://rp.baden-wuerttemberg.de/rpf/service/b...,NaN,NOBATCAPPLICABLE,NaN,NaN

In [96]:
ied_instal['InstallationInspireId'].value_counts()

InstallationInspireId
BE.WA/047010200.INSTALLATION                                                                74
BE.WA/047010100.INSTALLATION                                                                71
BE.WA/049010300.INSTALLATION                                                                59
BE.WA/049010500.INSTALLATION                                                                59
BE.WA/049010100.INSTALLATION                                                                59
                                                                                            ..
CZ.B/MZPDVHVYAGM2.INSTALLATION                                                               1
CZ.J/MZPJKHV2G0UH.INSTALLATION                                                               1
BG.CAED/008000068.INSTALLATION                                                               1
BG.CAED/013000087.INSTALLATION                                                               1
https://registry.gdi-de.org/id/de.th/5bf25e39-19d5-4254-adac-63f1b1cec499/92012847_555_0     1
Name: count, Length: 70847, dtype: int64

In [97]:
ied_instal['parent_facilityInspireId'].value_counts()

parent_facilityInspireId
https://registry.gdi-de.org/id/de.rp.inspire.pf.bube-eureg/5000671    1737
BE.WA/049010000.FACILITY                                               468
https://registry.gdi-de.org/id/de.by.inspire.pf.ied/S00114             440
https://registry.gdi-de.org/id/de.bb.inspire.pf.eureg/23020490         361
https://registry.gdi-de.org/id/de.ni.mu/06290168840                    315
                                                                      ...
LV.LVGMC.PRTR/RNLGYU.Facility                                            1
ES.CAED/011628000.FACILITY                                               1
ES.CAED/011629000.FACILITY                                               1
BG.CAED/017000030.FACILITY                                               1
CZ.E/MZPPCHX2E48A.FACILITY                                               1
Name: count, Length: 64041, dtype: int64

In [98]:
eprtr_classified.columns

Index(['PublicationDate', 'countryName', 'reportingYear', 'EPRTR_SectorCode',
       'EPRTR_SectorName', 'EPRTRAnnexIMainActivity', 'FacilityInspireId',
       'facilityName', 'city', 'Longitude', 'Latitude',
       'addressConfidentialityReason', 'TargetRelease', 'Pollutant',
       'Releases', 'confidentialityReason', 'ec', 'group', 'cas',
       'threshold_air_kg/year', 'threshold_water_kg/year',
       'threshold_land_kg/year', 'hap', 'cand_svhc', 'wfd_prio_sub', 'usetox',
       'iarc_group', 'clp_class'],
      dtype='object')

In [99]:
eprtr_classified['FacilityInspireId'].value_counts()

FacilityInspireId
NL.RIVM/000023301.FACILITY                                                                         656
FR.CAED/10845.FACILITY                                                                             616
FR.CAED/4473.FACILITY                                                                              559
https://data.ied_registry.omgeving.vlaanderen.be/id/productionfacility/BE.VL.000000605.FACILITY    557
FR.CAED/7656.FACILITY                                                                              535
                                                                                                  ...
NO.EEA/192329.FACILITY                                                                               1
DE.EEA/14-30-56050130000.FACILITY                                                                    1
NO.EEA/0937.0022.01.FACILITY                                                                         1
FR.EEA/064.00635.FACILITY                                                                            1
FR.CAED/8477.FACILITY                                                                                1
Name: count, Length: 32155, dtype: int64

In [100]:
ied_parent_duplicates = (
    ied_instal.loc[
        ied_instal["parent_facilityInspireId"]
        .duplicated(keep=False)
    ]
    .sort_values(
        [
            "parent_facilityInspireId",
            "InstallationInspireId",
        ]
    )
)

print(
    "IED installation rows:",
    len(ied_instal)
)

print(
    "Unique parent E‑PRTR facilities:",
    ied_instal["parent_facilityInspireId"].nunique()
)

print(
    "Parent facilities with multiple rows over multiple years:",
    ied_parent_duplicates[
        "parent_facilityInspireId"
    ].nunique()
)

ied_parent_duplicates[
    [
        "parent_facilityInspireId",
        "InstallationInspireId",
        "installationName",
        "installationStatus",
        "IEDAnnexIMainActivity",
        "IEDMainActivityName",
    ]
].sample(30)

IED installation rows: 477644
Unique parent E‑PRTR facilities: 64041
Parent facilities with multiple rows over multiple years: 62680

,parent_facilityInspireId,InstallationInspireId,installationName,installationStatus,IEDAnnexIMainActivity,IEDMainActivityName
51262,PL.MŚ/000003128.FACILITY,PL.MŚ/000003758.INSTALLATION,Kopalnia Gazu Ziemnego Szczepanów - Ośrodek Zb...,functional,1.1,Combustion of fuels in installations with a to...
265129,https://data.ied_registry.omgeving.vlaanderen....,https://data.ied_registry.omgeving.vlaanderen....,Evonik Antwerpen - AC,functional,4.1(b),Production of organic chemicals: oxygen-contai...
17310,CZ.U/MZPR98EJF343.FACILITY,CZ.U/MZPR98EJF343.INSTALLATION,Výkrmna brojlerových kuřat FARMA Křesín,functional,6.6(a),Intensive rearing of poultry with more than 40...
137337,IT.CAED/330502017.FACILITY,IT.CAED/330502017.INSTALLATION,"ZUCCOLO ENRICO, SERGIO E ANGELO SOCIETA' AGRIC...",functional,6.6(b),"Intensive rearing of pigs with more than 2,000..."
86034,NL.RIVM/000064345.FACILITY,NL.RIVM/000064345.INSTALLATION,Folding Boxboard Eerbeek bv,functional,6.1(b),Production in industrial installations of pape...
428854,FR.CAED/14393.FACILITY,FR.CAED/14393.INSTALLATION,SCO (MONIQUE RANOU),functional,6.4(b)(iii),"Treatment and processing, other than exclusive..."
123582,CZ.U/MZPR98EJBZ7N.FACILITY,CZ.U/MZPR98EJBZ7N.INSTALLATION,Speciální rámování autoskel,decommissioned,4.1(h),Production of organic chemicals: plastic mater...
274634,https://registry.gdi-de.org/id/de.he.0945.de7....,https://registry.gdi-de.org/id/de.he.0945.de7....,Anlage zumSchlachten von Geflügel,functional,6.4(a),Operating slaughterhouses with a carcass produ...
130227,NL.RIVM/000203707.FACILITY,NL.RIVM/000203707.INSTALLATION,Afvalstoffendienst gemeente 's-Hertogenbosch,functional,5.5,Temporary storage of hazardous waste not cover...
69256,https://registry.gdi-de.org/id/de.nw.inspire.p...,https://registry.gdi-de.org/id/de.nw.inspire.p...,Anlage zum Brennen von Kalkstein,functional,3.1(b),Production of lime in kilns with a production ...
23025,NL.RIVM/000202324.FACILITY,NL.RIVM/000202324.INSTALLATION,Nieuw Scheurlink V.O.F.,functional,6.6(a),Intensive rearing of poultry with more than 40...
196200,IT.CAED/260262006.FACILITY,IT.CAED/260262006.INSTALLATION,AZIENDA AGRICOLA SERENA DI LINGIARDI SANDRO FA...,functional,6.6(b),"Intensive rearing of pigs with more than 2,000..."
174972,FR.CAED/15232.FACILITY,FR.CAED/15232.INSTALLATION,CONTRAULT ARNAUD,functional,6.6(a),Intensive rearing of poultry with more than 40...
429625,ES.CAED/009925000.FACILITY,ES.CAED/009925000.INSTALLATION,ES220440000034-BAILO,functional,6.6(b),"Intensive rearing of pigs with more than 2,000..."
350044,https://registry.gdi-de.org/id/de.ni.mu/456001...,https://registry.gdi-de.org/id/de.ni.mu/456001...,Masthähnchen,functional,6.6(a),Intensive rearing of poultry with more than 40...
381218,https://registry.gdi-de.org/id/de.rp.inspire.p...,https://registry.gdi-de.org/id/de.rp.inspire.p...,Tiefdruckanlage,functional,6.7,"Surface treatment of substances, objects or pr..."
262878,NL.RIVM/000201645.FACILITY,NL.RIVM/000201645.INSTALLATION,Maatschap van Zutven,functional,6.6(a),Intensive rearing of poultry with more than 40...
270955,LT.CAED/111657920.FACILITY10,LT.CAED/111657920.INSTALLATION10,UAB „Idavang“ (02) Rupinskai branch,functional,6.6(b),"Intensive rearing of pigs with more than 2,000..."
171749,IT.CAED/250202024.FACILITY,IT.CAED/250202024.INSTALLATION,AZ. AGR. CAVAGNINI GIANFRANCO LUIGI E GIUSEPPE,functional,6.6(c),Intensive rearing of pigs with more than 750 p...
215989,ES.CAED/007708000.FACILITY,ES.CAED/007708000.INSTALLATION,ES502110000007-CERDOS-PLASENCIA DE JALÓN,functional,6.6(c),Intensive rearing of pigs with more than 750 p...
3309,https://registry.gdi-de.org/id/de.st.lau.pf.an...,https://registry.gdi-de.org/id/de.st.lau.pf.an...,Autowrackentsorgungsanlage,functional,5.1(b),Disposal or recovery of hazardous waste with a...
243427,UK.CAED/EW_EA-12821.FACILITY,UK.CAED/EW_EA-12821.INSTALLATION,Power Station Farm - EPR/AP3231KP,functional,6.6(a),Intensive rearing of poultry with more than 40...
260503,ES.CAED/008663000.FACILITY,ES.CAED/008663000.INSTALLATION,SOCIEDAD COOPERATIVA ADRIBAR,functional,6.6(b),"Intensive rearing of pigs with more than 2,000..."
138714,CZ.MZP.J632/CZ32775519.FACILITY,CZ.J/MZPR98EHVJQV.INSTALLATION,Farma pro odchov a výkrm prasat – středisko Ka...,functional,6.6(b),"Intensive rearing of pigs with more than 2,000..."
455964,FR.CAED/4678.FACILITY,FR.CAED/4678.INSTALLATION,SPECIALTY MINERALS FRANCE,functional,4.2(e),"Production of inorganic chemicals: non-metals,..."
425360,FR.CAED/31695.FACILITY,FR.CAED/31695.INSTALLATION,EARL PASTY DU BOIS,functional,6.6(a),Intensive rearing of poultry with more than 40...
360010,https://registry.gdi-de.org/id/de.nw.inspire.p...,https://registry.gdi-de.org/id/de.nw.inspire.p...,Klärschlammhochdeponie Veolia (ehemals Nuon),functional,5.4,"Landfills, as defined in Article 2(g) of Counc..."
11337,https://registry.gdi-de.org/id/de.st.lau.pf.an...,https://registry.gdi-de.org/id/de.st.lau.pf.an...,Mastgeflügelanlage Oppin 5,functional,6.6(a),Intensive rearing of poultry with more than 40...
412780,http://paikkatiedot.fi/so/1002031/pf/Productio...,http://paikkatiedot.fi/so/1002031/pf/Productio...,Rehu- ja tärkkelystehdas,functional,6.4(b)(ii),"Treatment and processing, other than exclusive..."
328431,https://registry.gdi-de.org/id/de.st.lau.pf.an...,https://registry.gdi-de.org/id/de.st.lau.pf.an...,"Zucht , Aufzucht , Mast von Schweinen",functional,6.6(c),Intensive rearing of pigs with more than 750 p...

In [101]:
releases = eprtr_classified.copy()
ied = ied_instal.copy()

In [102]:
# Ensure reporting years have the same dtype.
for table in [releases, ied]:
    table["reportingYear"] = (
        pd.to_numeric(table["reportingYear"], errors="raise")
        .astype("Int64")
    )

# Clean identifiers without changing the source tables.
releases["FacilityInspireId"] = (
    releases["FacilityInspireId"]
    .astype("string")
    .str.strip()
    .replace("", pd.NA)
)

ied["parent_facilityInspireId"] = (
    ied["parent_facilityInspireId"]
    .astype("string")
    .str.strip()
    .replace("", pd.NA)
)

ied["InstallationInspireId"] = (
    ied["InstallationInspireId"]
    .astype("string")
    .str.strip()
    .replace("", pd.NA)
)

keys = ["parent_facilityInspireId", "reportingYear"]

# Keep records with incomplete IED join keys separately for auditing.
ied_missing_keys = ied.loc[
    ied[keys].isna().any(axis=1)
].copy()

ied_valid = ied.dropna(subset=keys).copy()

In [103]:
ied_missing_keys.head(2)
ied_valid.head(2)

,PublicationDate,CountryName,reportingYear,parent_facilityInspireId,EPRTRAnnexIMainActivity,InstallationInspireId,installationName,installationNameConfidentialityReason,City_of_Facility,Longitude,...,permitGranted,dateOfGranting,permitReconsidered,permitUpdated,dateOfLastUpdate,permitURL,RelevantChapter,BATConclusion,BATAEL,BATAELStricterCondition
0,2026/02/13,Germany,2023,https://registry.gdi-de.org/id/de.rp.inspire.p...,4(a)(ii),https://registry.gdi-de.org/id/de.rp.inspire.p...,Glykol-Fabrik,NaN,Ludwigshafen am Rhein,8.43055,...,Yes,1900-01-01,Yes,No,1900-01-01,https://sgdsued.rlp.de/service/genehmigungen-u...,NaN,LVOC,NaN,NaN
1,2026/02/13,Germany,2023,https://registry.gdi-de.org/id/de.rp.inspire.p...,4(a)(ii),https://registry.gdi-de.org/id/de.rp.inspire.p...,Spezialitäten-Fabrik,NaN,Ludwigshafen am Rhein,8.42603,...,Yes,1900-01-01,Yes,No,1900-01-01,https://sgdsued.rlp.de/service/genehmigungen-u...,NaN,CWW,NaN,NaN

In [104]:
parent_year_summary = (
    ied_valid
    .groupby(keys, as_index=False)
    .agg(
        n_ied_rows=("InstallationInspireId", "size"),
        n_ied_installations=("InstallationInspireId", "nunique"),
        n_ied_rows_missing_installation_id=(
            "InstallationInspireId",
            lambda s: s.isna().sum(),
        ),
    )
)

multiple_installations = parent_year_summary.loc[
    parent_year_summary["n_ied_installations"] > 1
].copy()

In [105]:
yearly_counts = (
    parent_year_summary
    .assign(
        has_multiple_installations=lambda d: (
            d["n_ied_installations"] > 1
        )
    )
    .groupby("reportingYear", as_index=False)
    .agg(
        n_parent_facilities=("parent_facilityInspireId", "nunique"),
        n_parents_with_multiple_installations=(
            "has_multiple_installations",
            "sum",
        ),
    )
)

display(yearly_counts)

print(
    "Facility-year combinations with multiple installations:",
    len(multiple_installations),
)

print(
    "Distinct facilities with multiple installations in at least one year:",
    multiple_installations["parent_facilityInspireId"].nunique(),
)

   reportingYear  n_parent_facilities  n_parents_with_multiple_installations
0           2017                53088                                   2188
1           2018                54170                                   2258
2           2019                56975                                   2527
3           2020                52925                                   2574
4           2021                54354                                   2677
5           2022                54280                                   2698
6           2023                54338                                   2686
7           2024                52906                                   2659

Facility-year combinations with multiple installations: 20267
Distinct facilities with multiple installations in at least one year: 3065

In [106]:
def distinct_values(series):
    return series.dropna().drop_duplicates().tolist()

context_columns = [
    column
    for column in ied_valid.columns
    if column not in keys
]

ied_by_facility_year = (
    ied_valid
    .groupby(keys, as_index=False)
    .agg({
        column: distinct_values
        for column in context_columns
    })
    .rename(columns={
        column: f"{column}_ied"
        for column in context_columns
    })
    .merge(
        parent_year_summary,
        on=keys,
        how="left",
        validate="one_to_one",
    )
)

assert not ied_by_facility_year.duplicated(keys).any()

In [107]:
# def unique_text(values):
#     values = (
#         values
#         .dropna()
#         .astype("string")
#         .str.strip()
#     )

#     values = values[
#         values.notna()
#         & values.ne("")
#         & values.ne("<NA>")
#     ]

#     return " | ".join(
#         sorted(values.unique())
#     )

In [108]:
ied_columns = [
    "parent_facilityInspireId",
    "EPRTRAnnexIMainActivity",
    "InstallationInspireId",
    "installationName",
    "installationNameConfidentialityReason",
    "City_of_Facility",
    "Longitude",
    "Latitude",
    "addressConfidentialityReason",
    "installationStatus",
    "IEDAnnexIMainActivity",
    "IEDMainActivityName",
    "baselineReportIndicator",
    "siteVisitNumber",
    "siteVisitURL",
    "dateOfStartOfOperation",
    "publicEmissionMonitoring",
    "publicEmissionMonitoringURL",
    "permitGranted",
    "dateOfGranting",
    "permitReconsidered",
    "permitUpdated",
    "dateOfLastUpdate",
    "permitURL",
    "RelevantChapter",
    "BATConclusion",
    "BATAEL",
    "BATAELStricterCondition",
]

ied_selected = ied_instal[ied_columns].copy()

In [109]:
ied_aggregation = {
    column: distinct_values #unique_text
    for column in ied_selected.columns
    if column != "parent_facilityInspireId"
}

In [110]:
ied_by_parent_facility = (
    ied_selected
    .groupby(
        "parent_facilityInspireId",
        as_index=False,
        dropna=False,
    )
    .agg(ied_aggregation)
)

In [111]:
ied_by_parent_facility[
    "parent_facilityInspireId"
].duplicated().sum()

np.int64(0)

In [112]:
ied_by_parent_facility.columns

Index(['parent_facilityInspireId', 'EPRTRAnnexIMainActivity',
       'InstallationInspireId', 'installationName',
       'installationNameConfidentialityReason', 'City_of_Facility',
       'Longitude', 'Latitude', 'addressConfidentialityReason',
       'installationStatus', 'IEDAnnexIMainActivity', 'IEDMainActivityName',
       'baselineReportIndicator', 'siteVisitNumber', 'siteVisitURL',
       'dateOfStartOfOperation', 'publicEmissionMonitoring',
       'publicEmissionMonitoringURL', 'permitGranted', 'dateOfGranting',
       'permitReconsidered', 'permitUpdated', 'dateOfLastUpdate', 'permitURL',
       'RelevantChapter', 'BATConclusion', 'BATAEL',
       'BATAELStricterCondition'],
      dtype='object')

In [113]:
ied_by_parent_facility

,parent_facilityInspireId,EPRTRAnnexIMainActivity,InstallationInspireId,installationName,installationNameConfidentialityReason,City_of_Facility,Longitude,Latitude,addressConfidentialityReason,installationStatus,...,permitGranted,dateOfGranting,permitReconsidered,permitUpdated,dateOfLastUpdate,permitURL,RelevantChapter,BATConclusion,BATAEL,BATAELStricterCondition
0,AT.CAED/9008390237748.FACILITY,[4(a)],[AT.CAED/9008391189732.INSTALLATION],[NOCH NICHT MIGRIERT: Erzeugung von Kunstharzp...,[],[Werndorf],[15.481861],[46.916667],[],[functional],...,[Yes],[1997-06-24],"[Yes, No]",[No],[1900-01-01],[],[ChapterV],"[WGC, LVOC]",[],[]
1,AT.CAED/9008390301753.FACILITY,[6(b)],[AT.CAED/9008391299837.INSTALLATION],[Papiererzeugung],[],[Stattersdorf],[15.637778],[48.196556],[],[functional],...,[Yes],[2000-09-19],"[No, Yes]",[No],[1900-01-01],[],[],[PP],[],[]
2,AT.CAED/9008390306826.FACILITY,[6(a)],[AT.CAED/9008391295341.INSTALLATION],[Zellstoffherstellung],[],[Kematen],[14.761917],[48.026167],[],[functional],...,[Yes],[2015-04-22],"[No, Yes]",[No],[1900-01-01],[],[],[PP],[],[]
3,AT.CAED/9008390316955.FACILITY,[6(b)],[AT.CAED/9008391658320.INSTALLATION],[Papierherstellung],[],[Kematen],[14.761917],[48.026167],[],[functional],...,[Yes],[2016-02-11],"[No, Yes]",[No],[1900-01-01],[],[],[PP],[],[]
4,AT.CAED/9008390317211.FACILITY,[6(b)],[AT.CAED/9008391658139.INSTALLATION],[Papierherstellung],[],[Hausmening],[14.808389],[48.070278],[],[functional],...,[Yes],[2010-05-05],"[No, Yes]",[No],[1900-01-01],[],[ChapterIII],[PP],[],[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64036,https://registry.gdi-de.org/id/de.th/5bf25e39-...,[7(a)(i)],[https://registry.gdi-de.org/id/de.th/5bf25e39...,[Junghennenanlage],[],[Berlstedt],[11.22551],[51.03569],[],[functional],...,[Yes],"[1992-07-07, 1900-01-01]",[No],[No],"[2004-11-11, 1900-01-01]",[https://weimarerland.de/landwirtschaft/index....,[],[IRPP],[],[]
64037,https://registry.gdi-de.org/id/de.th/5bf25e39-...,[5(a)],[https://registry.gdi-de.org/id/de.th/5bf25e39...,[Kühlschrankrecycling],[],[Blankenhain],[11.43802],[50.84993],[],[functional],...,[Yes],[1900-01-01],[No],[No],"[2013-12-20, 1900-01-01]",[https://tlubn.thueringen.de/umweltschutz/immi...,[],[WT],[],[]
64038,https://registry.gdi-de.org/id/de.th/5bf25e39-...,[7(a)(iii)],[https://registry.gdi-de.org/id/de.th/5bf25e39...,[Sauenzuchtanlage],[],[Ilmtal-Weinstraße],[11.45893],[51.09318],[],[functional],...,[Yes],"[2012-06-27, 1900-01-01]",[No],[No],[1900-01-01],[https://tlubn.thueringen.de/umweltschutz/immi...,[],[IRPP],[],[]
64039,https://registry.gdi-de.org/id/de.th/5bf25e39-...,[9(c)],[https://registry.gdi-de.org/id/de.th/5bf25e39...,[Druckerei],[],[Am Ettersberg],[11.34098],[51.00579],[],"[functional, notRegulated]",...,[Yes],"[2013-08-29, 1900-01-01]",[No],[No],"[2014-08-09, 1900-01-01]",[https://tlubn.thueringen.de/umweltschutz/immi...,[ChapterV],"[NOBATCAPPLICABLE, BATCNOTYETADOPTED]",[],[]
64040,https://registry.gdi-de.org/id/de.th/5bf25e39-...,[5(a)],[https://registry.gdi-de.org/id/de.th/5bf25e39...,"[Vakuumthermik, Lagerung von büA, Behandlung v...",[],[Rositz],[12.38739],[50.82906],[],"[decommissioned, functional]",...,"[Yes, No]",[1900-01-01],[No],[No],[1900-01-01],[https://tlubn.thueringen.de/umweltschutz/immi...,[],[WT],[],[]

In [114]:
ied_multiple_installations = (
    ied_by_facility_year.loc[
        ied_by_facility_year["n_ied_installations"] > 1
    ]
    .sort_values(
        ["reportingYear", "parent_facilityInspireId"]
    )
    .copy()
)

In [115]:
ied_multiple_installations

,parent_facilityInspireId,reportingYear,PublicationDate_ied,CountryName_ied,EPRTRAnnexIMainActivity_ied,InstallationInspireId_ied,installationName_ied,installationNameConfidentialityReason_ied,City_of_Facility_ied,Longitude_ied,...,permitUpdated_ied,dateOfLastUpdate_ied,permitURL_ied,RelevantChapter_ied,BATConclusion_ied,BATAEL_ied,BATAELStricterCondition_ied,n_ied_rows,n_ied_installations,n_ied_rows_missing_installation_id
231,AT.CAED/9008390402368.FACILITY,2017,[2026/02/13],[Austria],[8(b)],"[AT.CAED/9008391627722.INSTALLATION, AT.CAED/9...","[Produktionsanlagen mit Energieanlagen, Gipsd...",[],[Wulzeshofen],[16.278111],...,[No],[1900-01-01],[],[ChapterIII],"[FDM, NOBATCAPPLICABLE]",[],[],2,2,0
247,AT.CAED/9008390402535.FACILITY,2017,[2026/02/13],[Austria],[2(e)],"[AT.CAED/9008390884669.INSTALLATION, AT.CAED/9...","[Recycling 1 (früher ""Nickelröstanlage"" genann...",[],[Treibach],"[14.459194, 14.460556, 14.461667, 14.463611, 1...",...,[No],[1900-01-01],[],[ChapterIV],"[BATCNOTYETADOPTED, CWW, NFM, NOBATCAPPLICABLE]",[],[],8,8,0
435,AT.CAED/9008390416235.FACILITY,2017,[2026/02/13],[Austria],[2(c)],"[AT.CAED/9008391184706.INSTALLATION, AT.CAED/9...","[Oberflächenbehandlung, Feuerverzinkung]",[],[Mühltal],[13.93125],...,[No],[1900-01-01],[http://www.edm.gv.at],[],[BATCNOTYETADOPTED],[],[],2,2,0
625,AT.CAED/9008390470305.FACILITY,2017,[2026/02/13],[Austria],[6(b)],"[AT.CAED/9008391028659.INSTALLATION, AT.CAED/9...","[Formaldehydharzherstellung, Span- u. Faserpla...",[],[Siezenheim],[12.999861],...,[No],[1900-01-01],[],[ChapterIV],"[LVOC, PP]",[],[],2,2,0
860,AT.CAED/9008390509852.FACILITY,2017,[2026/02/13],[Austria],[3(c)],"[AT.CAED/9008391276616.INSTALLATION, AT.CAED/9...","[Zementwerk Wopfing, Kalkwerk]",[],[Wopfing],"[16.085, 16.084944]",...,[No],[1900-01-01],[],[ChapterIV],[CLM],[],[],2,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
432831,https://registry.gdi-de.org/id/de.th/5bf25e39-...,2024,[2026/02/13],[Germany],[2(e)(ii)],[https://registry.gdi-de.org/id/de.th/5bf25e39...,"[Alu-Gießerei (Druckgießmaschinenanlage), Schm...",[],[Gerstungen],[10.04781],...,[No],[1900-01-01],[https://tlubn.thueringen.de/umweltschutz/immi...,[],[NOBATCAPPLICABLE],[],[],2,2,0
432853,https://registry.gdi-de.org/id/de.th/5bf25e39-...,2024,[2026/02/13],[Germany],[5(a)],[https://registry.gdi-de.org/id/de.th/5bf25e39...,"[Behandlung gefährlicher Abfälle, Zwischenlag...",[],[Dermbach],[10.12725],...,[No],[1900-01-01],[https://tlubn.thueringen.de/umweltschutz/immi...,[],[WT],[],[],2,2,0
432953,https://registry.gdi-de.org/id/de.th/5bf25e39-...,2024,[2026/02/13],[Germany],[2(e)(ii)],[https://registry.gdi-de.org/id/de.th/5bf25e39...,"[Stranggußanlage für Rotguß, Rotgußschmelze]",[],[Großheringen],[11.65682],...,[No],[1900-01-01],[https://tlubn.thueringen.de/umweltschutz/immi...,[],"[NFM, NOBATCAPPLICABLE]",[],[],2,2,0
432963,https://registry.gdi-de.org/id/de.th/5bf25e39-...,2024,[2026/02/13],[Germany],[7(a)(iii)],[https://registry.gdi-de.org/id/de.th/5bf25e39...,"[Biogasanlage, Sauenzuchtanlage]",[],[Neumark],"[11.24564, 11.24632]",...,[No],[1900-01-01],[https://tlubn.thueringen.de/umweltschutz/immi...,[],"[WT, IRPP]",[],[],2,2,0
433035,https://registry.gdi-de.org/id/de.th/5bf25e39-...,2024,[2026/02/13],[Germany],[5(a)],[https://registry.gdi-de.org/id/de.th/5bf25e39...,"[Vakuumthermik, Behandlung von Abfällen, Lager...",[],[Rositz],[12.38739],...,[No],[1900-01-01],[https://tlubn.thueringen.de/umweltschutz/immi...,[],[WT],[],[],3,3,0

## Merging IED to EPRTR

In [116]:
df_eprtr = releases.merge(
    ied_by_facility_year,
    how="left",
    left_on=["FacilityInspireId", "reportingYear"],
    right_on=["parent_facilityInspireId", "reportingYear"],
    validate="many_to_one",
    indicator="ied_facility_year_match",
)

# A facility-year summary should never multiply release rows.
assert len(df_eprtr) == len(releases)

In [117]:
df_eprtr.columns

Index(['PublicationDate', 'countryName', 'reportingYear', 'EPRTR_SectorCode',
       'EPRTR_SectorName', 'EPRTRAnnexIMainActivity', 'FacilityInspireId',
       'facilityName', 'city', 'Longitude', 'Latitude',
       'addressConfidentialityReason', 'TargetRelease', 'Pollutant',
       'Releases', 'confidentialityReason', 'ec', 'group', 'cas',
       'threshold_air_kg/year', 'threshold_water_kg/year',
       'threshold_land_kg/year', 'hap', 'cand_svhc', 'wfd_prio_sub', 'usetox',
       'iarc_group', 'clp_class', 'parent_facilityInspireId',
       'PublicationDate_ied', 'CountryName_ied', 'EPRTRAnnexIMainActivity_ied',
       'InstallationInspireId_ied', 'installationName_ied',
       'installationNameConfidentialityReason_ied', 'City_of_Facility_ied',
       'Longitude_ied', 'Latitude_ied', 'addressConfidentialityReason_ied',
       'installationStatus_ied', 'IEDAnnexIMainActivity_ied',
       'IEDMainActivityName_ied', 'baselineReportIndicator_ied',
       'siteVisitNumber_ied', 'siteVisitURL_ied', 'dateOfStartOfOperation_ied',
       'publicEmissionMonitoring_ied', 'publicEmissionMonitoringURL_ied',
       'permitGranted_ied', 'dateOfGranting_ied', 'permitReconsidered_ied',
       'permitUpdated_ied', 'dateOfLastUpdate_ied', 'permitURL_ied',
       'RelevantChapter_ied', 'BATConclusion_ied', 'BATAEL_ied',
       'BATAELStricterCondition_ied', 'n_ied_rows', 'n_ied_installations',
       'n_ied_rows_missing_installation_id', 'ied_facility_year_match'],
      dtype='object')

In [79]:
df_eprtr

,PublicationDate,countryName,reportingYear,EPRTR_SectorCode,EPRTR_SectorName,EPRTRAnnexIMainActivity,FacilityInspireId,facilityName,city,Longitude,...,dateOfLastUpdate_ied,permitURL_ied,RelevantChapter_ied,BATConclusion_ied,BATAEL_ied,BATAELStricterCondition_ied,n_ied_rows,n_ied_installations,n_ied_rows_missing_installation_id,ied_facility_year_match
0,2026/02/13,Germany,2013,1.0,Energy sector,1(e),https://registry.gdi-de.org/id/de.nw.inspire.p...,RWE Power AG-Fabrik Fortuna Nord,Bergheim,6.658050,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1,2026/02/13,Sweden,2020,7.0,Intensive livestock production and aquaculture,7(a)(i),SE.CAED/10017896.Facility,Skåneägg Produktion AB,MÖRARP,12.849550,...,[1900-01-01],[https://jordbruksverket.se/kontroller-och-til...,[],[IRPP],[],[],1.0,1.0,0.0,both
2,2026/02/13,Romania,2013,5.0,Waste and wastewater management,5(d),RO.CAED/104TL0001.FACILITY,SC ECOREC SA,TULCEA,28.769671,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3,2026/02/13,Italy,2021,7.0,Intensive livestock production and aquaculture,7(a),IT.CAED/370602036.FACILITY,RONCHETRIN 1,GAZZO VERONESE,11.106667,...,[1900-01-01],[https://portale.provincia.vr.it/index.php/ser...,[],[IRPP],[],[],1.0,1.0,0.0,both
4,2026/02/13,Czechia,2007,1.0,Energy sector,1(c),CZ.MZP.U423/CZ14819275.FACILITY,energetika,Štětí,14.380370,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
626357,2026/02/13,Norway,2008,7.0,Intensive livestock production and aquaculture,7(b),NO.EEA/1547.0030.02.FACILITY,"Aukrasanden, matfisk",Bergen,6.926050,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
626358,2026/02/13,Netherlands,2018,5.0,Waste and wastewater management,5(c),NL.RIVM/000114740.FACILITY,RWZI Susteren,Susteren,5.833590,...,[1900-01-01],[http://www.rudzuidlimburg.nl/bedrijven/vergun...,[],[BATCNOTYETADOPTED],[],[],1.0,1.0,0.0,both
626359,2026/02/13,United Kingdom,2014,1.0,Energy sector,1(c),UK.CAED/BEISOffsh-Clyde.FACILITY,Clyde Alpha,--,2.288330,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
626360,2026/02/13,Spain,2021,5.0,Waste and wastewater management,5(f),ES.CAED/007766000.FACILITY,EDAR LA LLAGOSTA,"Llagosta, La",2.202064,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
626361,2026/02/13,Germany,2024,5.0,Waste and wastewater management,5(f),https://registry.gdi-de.org/id/de.bw.lubw.insp...,SKA Heilbronn,Heilbronn,9.216570,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

## Availability USEtox

## Streamlit Table: Query Dashboard

## General Cleaning Cell

## Merging Cell

## Matching reported industrial pollutatns to REACH, CLP hazard and risk labels

## Missing Pollution: Research focus on agricultural & chemical industries

## Filtering, limiting dataset to those two sectors only: 'A' and 'B'